### ISSUE TITLE
Support for newer gpus

### ISSUE THREAD

**Issue by protonesso** [envytools/firmware#4]
Hi, I'm interested in your project. I can't use Nvidia's blob on musl Linux system so I decided to use blob's firmware packages instead of nouveau's, but it supports older cards. Can be support for newer card added right now? Thanks for attention.

**Comment by imirkin** [comment]
Are you referring to video decoding specifically? That would require a lot more than extracting firmware, but as always, patches welcome!

**Comment by protonesso** [comment]
No, I'm considering it as linux-firmware's blob replacements. I want to ask, any significant changes in perfomance with using blob's firmware? If so that would be great!

**Comment by imirkin** [comment]
Blob firmware would allow nouveau to do reclocking, however that would have to be hooked up. There's currently no effort under way that I'm aware to do any of that.
