### ISSUE TITLE
extract_firmware.py exits with error using 325.15

### ISSUE THREAD

**Issue by mahiuchun** [envytools/firmware#5]
All other versions seem fine.

fwiw, https://nouveau.freedesktop.org/wiki/VideoAcceleration/#firmware is giving instruction using 325.15.

**Comment by imirkin** [comment]
OK, that's bad. 325.15 is the good one. This used to work. Is this with your py2->3 changes? Or even before that, and I broke it somehow?

**Comment by mahiuchun** [comment]
Before that, like with a0dbfef944d49ac7d81a0dd51722a9bb83de7098 and py2. The error comes from the block of code after "Unknown PGRAPH archive order in this version." which is not present in the `re-vp2` version.

**Comment by imirkin** [comment]
Heh, yeah, I screwed it up when I added the dumping of "unknown" pgraph files. I just return in the middle of that function ... oops! Will fix shortly.

**Comment by imirkin** [comment]
OK, fixed by 7d29d955ef9cf086713e5f1820d0eee1c54b80aa
